# Generated by Django 3.2.18 on 2023-02-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
